name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/notie-backend
            git pull origin main
            /home/ubuntu/.local/bin/uv sync
            sudo systemctl restart notie
            echo "User:"
            whoami
            echo "Hostname:"
            hostname
            echo "Full host info:"
            hostnamectl || uname -a

